# action.yml
name: Http Polling
author: yao
description: "Wait for response code from a URL with timeout"
inputs:
  url:
    description: URL to poll
    required: true
  timeout:
    description: "Timeout before giving up in seconds"
    required: false
    default: 900
  interval:
    description: "Interval between polling in seconds"
    required: false
    default: 60
  token:
    description: "Secret used for authentication"
    required: true
outputs:
  result:
    description: outputs the response from the call
runs:
  using: "composite"
  steps:
    - id: main
      run: |
        echo "${GITHUB_ACTION_PATH}"
        echo "${{ github.action_path }}"
        timeout ${{inputs.timeout }} ${GITHUB_ACTION_PATH}/main.sh \
        --url="${{ inputs.url }}" \
        --interval="${{ inputs.interval }}" \
        --token="${{ inputs.token }}"\
      shell: bash
